#!/bin/bash
# Crear un script bash o makefile, que acepte parámetros (CREATE, DESTROY y OUTPUT) con los siguientes pasos:
# Load the user defined parameters
while [[ $# > 0 ]]
do
        case "$1" in
                -a|-p)
                        valA="$2"
                        shift
                        ;;
                -b|-tf)
                        valB="$2"
                        shift
                        ;;
		-c|--valueC)
                        valC="$2"
                        shift
                        ;;
                --help|*)
                        echo "Usage:"
			echo "------"
                        echo "    --help: for Help "
			cat  README.md | more
                        exit 1
                        ;;
		*)
                        echo "Usage:"
                        echo "------"
                        echo "    --help: for Help "
                        cat  README.md | more
                        exit 1
                        ;;
        esac
        shift
done
if [ $valA == "CREATE" ]  ; then
	if [ $valB == "L" ]  ; then
		echo "CREATE + TFLINUX"
		   cd scripts/
		   ./tf_Linux 
		echo "----------------Permit Access to your Google Platform---------------------"
        	  gcloud auth application-default login 
	     	echo "----------------Select a Project -----------------------------------------"
		   gcloud projects list
		   gcloud init 
		echo "----------------Enter Project---------------------------------------------"
		echo "----------------Select copy and Paste Project Name------------------------"
		read ValProject	
		echo "----------------Make variables.tf-----------------------------------------"
echo '		
variable "name" {
  default = "demo-cluster"
}

variable "project" {
  default = "'$ValProject'"
}

variable "location" {
  default = "us-central1"
}

variable "initial_node_count" {
  default = 1
}

variable "machine_type" {
  default = "n1-standard-1"
}' > ../terraform-gke/variables.tf 
	
       	 	echo "----------------Deploy cluster--------------------------------------------"
		cd ../terraform-gke
		terraform init -reconfigure
        	terraform plan
        	terraform apply
		echo "-----------------gcloud --------------------------------------------------"
		gcloud container clusters list
		gcloud container clusters get-credentials demo-cluster --region us-central1 --project $ValProject
		echo "-----------------Verify kubectl-------------------------------------------"
		#./verify /usr/bin/kubectl 
		# verify kubectl 
		#cd ~/challenge/terraform-gke/
		#cd terraform-gke
		pwd
		cd  ../terraform-gke/app
	       	kubectl apply -f deployment.yaml
		kubectl apply -f 12service.yaml
		#Ingress for expose 
		kubectl apply -f 12ingress.yaml
		echo "-----------------Wait...... building ingress-----------------------------"
                sleep 420
                kubectl get ing
	elif
	[ $valB == "M" ]  ; then
		echo "CREATE + TFMAC"
		#   ~/challenge/scripts/tf_MacOS
                echo "----------------Permit Access to your Google Platform---------------------"
                   gcloud auth application-default login       
                echo "----------------Deploy cluster--------------------------------------------"
                   cd terraform-gke
		terraform init -reconfigure   
                terraform plan
                terraform apply
	fi
fi
if [ $valA == "DESTROY" ]  ; then
		echo "DESTROY"
		cd terraform-gke
		terraform destroy
fi
if [ $valA == "OUTPUT" ]  ; then
		echo "OUTPUT"


fi






	



